name: Fortran CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - run: |
          cd source
          mkdir build
          mkdir lib
          make
          make build
          make install
